version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.30.0-focal
    # Steps to the job
    steps:
      - checkout
      - run: 
          name: Install npm Playwright
          command: npm i -D @playwright/test
      - run: 
          name: Install Playwright
          command: npx playwright install
      - run: npx playwright install
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit --project=chromium
      - store_test_results:
          path: results.xml
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test