version: 2.1

executors:
  plugin-e2e-tester:
    docker:
      - image: cimg/node:14.15.0-browsers
    working_directory: ~/repo
    resource_class: medium+
      
jobs:      
  plugin-e2e-test:
    executor: plugin-e2e-tester
    parallelism: 1
    steps:
      - checkout
      - run: 
        name: Install npm playwright
        ommand: | 
            npm i -D @playwright/test  
      - run:
          name: Install playwright
          command: |
            npx playwright install --with-deps chromium
      - run:
          name: Run E2E tests
          command: |
            npx playwright test
          environment:
            PLAYWRIGHT_JUNIT_OUTPUT_DIR: ~/repo/apps/plugin/e2e/reports/junit/
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml

      - store_test_results:
          path: ~/repo/apps/plugin/e2e/reports/junit

      - store_artifacts:
          path: ~/repo/apps/plugin/e2e/recordings
          destination: artifacts


workflows:
  version: 2
  all:
    jobs:
      - plugin-e2e-test